name: Build

on:
  push:
    branches:
    - master
    - dev
    paths-ignore:
      - '*.md'
      - LICENSE
  pull_request:
    branches:
    - master
    - dev
    paths-ignore:
      - '*.md'
      - LICENSE

jobs:
  build:
    runs-on: ${{ matrix.os.name }}
    strategy:
      # we want to run the full build on all os: don't cancel running jobs even if one fails
      fail-fast: false
      matrix:
        # syntax inspired from https://github.community/t5/GitHub-Actions/Using-a-matrix-defined-input-for-a-custom-action/m-p/32032/highlight/true#M988
        os:
          - {name: macos-10.15, short: "macos" }
          - {name: windows-2019, short: "windows" }
          - {name: ubuntu-20.04, short: "ubuntu" }
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Setup Maven configuration
      shell: bash
      run: |
        mkdir -p $HOME/.m2/
        cp $GITHUB_WORKSPACE/.github/workflows/maven/settings.xml $HOME/.m2/
    - name: Build without Studio
      shell: bash
      run: ./build-script.sh
      env:
        BONITA_BUILD_QUIET: true
        BONITA_BUILD_STUDIO_SKIP: true
    - name: Upload Bonita bundle
      # see https://help.github.com/en/github/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts and https://github.com/actions/upload-artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        # see https://github.community/t5/GitHub-Actions/Use-variables-in-upload-artifact/m-p/34778#M2009
        name: bonita-bundle-${{matrix.os.short}}-build-${{github.sha}}
        path: bonita-distrib/tomcat/target/*.zip
    - name: Build Studio
      shell: bash
      run: ./build-script.sh
      env:
        BONITA_BUILD_QUIET: true
        BONITA_BUILD_STUDIO_ONLY: true
    - name: Upload Bonita Studio
      # see https://github.com/actions/upload-artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        name: bonita-studio-${{matrix.os.short}}-build-${{github.sha}}
        path: bonita-studio/all-in-one/target/*.zip
